# MCU name
MCU = RP2040
# Bootloader selection
BOOTLOADER = rp2040

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

BOOTMAGIC_ENABLE = yes

LTO_ENABLE = no

EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
SWAP_HANDS_ENABLE = no
MOUSEKEY_ENABLE = no
AUDIO_ENABLE = no
QMK_SETTINGS = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = ws2812
WS2812_DRIVER = vendor

# OLED
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
WPM_ENABLE = no

